server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    if ($host = shop.reignstide.org) {
      rewrite ^/$ /shop.html last;
    }
    try_files $uri $uri/ =404;
  }
}
